package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GBag generated by hbm2java
 */
@Entity
@Table(name = "g_area", catalog = "zero")
public class GArea implements java.io.Serializable {

	private String id;
	private String name;
	private int totalNum;
	private int onlineNum;
	private int offlineNum;
	private long createTime;
	@Id 
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@Column(name = "name", length = 50)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "total_num")
	public int getTotalNum() {
		return totalNum;
	}
	public void setTotalNum(int totalNum) {
		this.totalNum = totalNum;
	}
	@Column(name = "online_num")
	public int getOnlineNum() {
		return onlineNum;
	}
	public void setOnlineNum(int onlineNum) {
		this.onlineNum = onlineNum;
	}
	@Column(name = "offline_num")
	public int getOfflineNum() {
		return offlineNum;
	}
	public void setOfflineNum(int offlineNum) {
		this.offlineNum = offlineNum;
	}
	@Column(name = "create_time")
	public long getCreateTime() {
		return createTime;
	}
	public void setCreateTime(long createTime) {
		this.createTime = createTime;
	}
	
}
