package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.cross.GBagItem;

/**
 * GBag generated by hbm2java
 */
@Entity
@Table(name = "g_bag", catalog = "zero")
public class GBag implements java.io.Serializable {

	private String id;
	private String name;
	private String detail;
	private Integer grid;
	private Set<GBagItem> bag_item;
	@OneToMany(fetch = FetchType.LAZY)  
	@JoinColumn(name="bag_id")  
	@NotFound(action=NotFoundAction.IGNORE)
	public Set<GBagItem> getBag_item() {
		return bag_item;
	}

	public void setBag_item(Set<GBagItem> bag_item) {
		this.bag_item = bag_item;
	}

	public GBag() {
	}

	public GBag(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "grid")
	public Integer getGrid() {
		return this.grid;
	}

	public void setGrid(Integer grid) {
		this.grid = grid;
	}

}
