package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GBuilding generated by hbm2java
 */
@Entity
@Table(name = "g_building", catalog = "zero")
public class GBuilding implements java.io.Serializable {

	private String id;
	private String name;
	private String detail;
	private String landId;
	@Column(name="land_id",length=32)
	public String getLandId() {
		return landId;
	}

	public void setLandId(String landId) {
		this.landId = landId;
	}

	public GBuilding() {
	}

	public GBuilding(String id) {
		this.id = id;
	}

	public GBuilding(String id, String name, String detail) {
		this.id = id;
		this.name = name;
		this.detail = detail;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
