package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.zzy.base.BaseEntity;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.cross.GEquipItem;

/**
 * GEquip generated by hbm2java
 */
@Entity
@Table(name = "g_equip", catalog = "zero")
public class GEquip  extends BaseEntity implements java.io.Serializable {

	private String id;
	private String detail;
	private String name;
	private Set<GEquipItem> equip_item;
	@OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name="equip_id",unique=true)
	@NotFound(action=NotFoundAction.IGNORE)  
	public Set<GEquipItem> getEquip_item() {
		return equip_item;
	}

	public void setEquip_item(Set<GEquipItem> equip_item) {
		this.equip_item = equip_item;
	}

	public GEquip() {
	}

	public GEquip(String id) {
		this.id = id;
	}

	public GEquip(String id, String detail, String name) {
		this.id = id;
		this.detail = detail;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
