package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import com.zzy.base.BaseEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GItems generated by hbm2java
 */
@Entity
@Table(name = "g_items", catalog = "zero")
public class GItems  extends BaseEntity implements java.io.Serializable {

	private String id;
	private String detail;
	private String name;
	private Integer level;
	private Integer quality;
	private Integer type;
	private String icon;
	private Integer status;
	private Integer strength;
	private Integer agility;
	private Integer intellect;
	private Integer lucky;
	private String profile;
	private Integer property;
	private Integer price;

	public GItems() {
	}

	public GItems(String id) {
		this.id = id;
	}

	public GItems(String id, String detail, String name, Integer level, Integer quality, Integer type, String icon, Integer status,
			Integer strength, Integer agility, Integer intellect, Integer lucky, String profile, Integer property, Integer price) {
		this.id = id;
		this.detail = detail;
		this.name = name;
		this.level = level;
		this.quality = quality;
		this.type = type;
		this.icon = icon;
		this.status = status;
		this.strength = strength;
		this.agility = agility;
		this.intellect = intellect;
		this.lucky = lucky;
		this.profile = profile;
		this.property = property;
		this.price = price;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "quality")
	public Integer getQuality() {
		return this.quality;
	}

	public void setQuality(Integer quality) {
		this.quality = quality;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "icon", length = 50)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public GItems setStatus(Integer status) {
		this.status = status;
		return this;
	}

	@Column(name = "strength")
	public Integer getStrength() {
		return this.strength;
	}

	public void setStrength(Integer strength) {
		this.strength = strength;
	}

	@Column(name = "agility")
	public Integer getAgility() {
		return this.agility;
	}

	public void setAgility(Integer agility) {
		this.agility = agility;
	}

	@Column(name = "intellect")
	public Integer getIntellect() {
		return this.intellect;
	}

	public void setIntellect(Integer intellect) {
		this.intellect = intellect;
	}

	@Column(name = "lucky")
	public Integer getLucky() {
		return this.lucky;
	}

	public void setLucky(Integer lucky) {
		this.lucky = lucky;
	}

	@Column(name = "profile", length = 50)
	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

	@Column(name = "property")
	public Integer getProperty() {
		return this.property;
	}

	public void setProperty(Integer property) {
		this.property = property;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}
