package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.zzy.base.BaseEntity;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * GLand generated by hbm2java
 */
@Entity
@Table(name = "g_land", catalog = "zero")
public class GLand  extends BaseEntity implements java.io.Serializable {

	private String id;
	private String name;
	private String detail;
	private Integer size;
	private String roleId;
	private long startTime;
	private long endTime;
	private long ownTime;
	private Integer isRent;
	private Set<GBuilding> build;

	@OneToMany(fetch = FetchType.LAZY)   
	@JoinColumn(name="land_id") 
	@NotFound(action=NotFoundAction.IGNORE)
	public Set<GBuilding> getBuild() {
		return build; 
	}

	public void setBuild(Set<GBuilding> build) {
		this.build = build;
	}

	public GLand() {
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@Column(name = "start_time", nullable = false, length = 19)
	public long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(long startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time", nullable = false, length = 19)
	public long getEndTime() {
		return this.endTime;
	}

	public void setEndTime(long endTime) {
		this.endTime = endTime;
	}

	@Column(name = "own_time", nullable = false, length = 19)
	public long getOwnTime() {
		return this.ownTime;
	}

	public void setOwnTime(long ownTime) {
		this.ownTime = ownTime;
	}

	@Column(name = "is_rent")
	public Integer getIsRent() {
		return this.isRent;
	}

	public void setIsRent(Integer isRent) {
		this.isRent = isRent;
	}

}
