package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.zzy.domain.cross.GSkillBuff;

/**
 * GSkill generated by hbm2java
 */
@Entity
@Table(name = "g_skill", catalog = "zero")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class GSkill implements java.io.Serializable {

	private String id;
	private String detail;
	private String name;
	private Integer level;
	private Integer type;
	private Integer time;
	private Integer scope;
	private Integer requirement;
	private Integer targetTypee;
	private Integer targetNum;
	private Set<GSkillBuff> skill_buff;
	@OneToMany(fetch = FetchType.LAZY)   
	@JoinColumn(name="skill_id") 
	@NotFound(action=NotFoundAction.IGNORE)
	public Set<GSkillBuff> getSkill_buff() {
		return skill_buff;
	}

	public void setSkill_buff(Set<GSkillBuff> skill_buff) {
		this.skill_buff = skill_buff;
	}

	public GSkill() {
	}

	public GSkill(String id) {
		this.id = id;
	}

	public GSkill(String id, String detail, String name, Integer level, Integer type, Integer time, Integer scope,
			Integer requirement, Integer targetTypee, Integer targetNum) {
		this.id = id;
		this.detail = detail;
		this.name = name;
		this.level = level;
		this.type = type;
		this.time = time;
		this.scope = scope;
		this.requirement = requirement;
		this.targetTypee = targetTypee;
		this.targetNum = targetNum;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "time")
	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	@Column(name = "scope")
	public Integer getScope() {
		return this.scope;
	}

	public void setScope(Integer scope) {
		this.scope = scope;
	}

	@Column(name = "requirement")
	public Integer getRequirement() {
		return this.requirement;
	}

	public void setRequirement(Integer requirement) {
		this.requirement = requirement;
	}

	@Column(name = "target_typee")
	public Integer getTargetTypee() {
		return this.targetTypee;
	}

	public void setTargetTypee(Integer targetTypee) {
		this.targetTypee = targetTypee;
	}

	@Column(name = "target_num")
	public Integer getTargetNum() {
		return this.targetNum;
	}

	public void setTargetNum(Integer targetNum) {
		this.targetNum = targetNum;
	}

}
