package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.zzy.base.BaseEntity;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.zzy.domain.cross.GVocationSkill;

/**
 * GVocation generated by hbm2java
 */
@Entity
@Table(name = "g_vocation", catalog = "zero")
@JsonIgnoreProperties({"role"})
public class GVocation  extends BaseEntity implements java.io.Serializable {
 
	private String id;
	private String detail;
	private String name; 
    private Set<GVocationSkill> vocation_kill;
    
    @OneToMany(fetch = FetchType.LAZY)   
	@JoinColumn(name="vocation_id") 
	@NotFound(action=NotFoundAction.IGNORE)
    public Set<GVocationSkill> getVocation_kill() {
		return vocation_kill;
	}

	public void setVocation_kill(Set<GVocationSkill> vocation_kill) {
		this.vocation_kill = vocation_kill;
	}




	public GVocation() {
	}



	public GVocation(String id) {
		this.id = id;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
