package com.zzy.domain.base;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.cross.ZPositionPower;

/**
 * ZPosition generated by hbm2java
 */
@Entity
@Table(name = "z_position", catalog = "zero")
public class ZPosition implements java.io.Serializable {

	private String id;
	private String name;
	private String detail;
	private Set<ZPositionPower> position_power;
	@OneToMany(fetch = FetchType.LAZY)  
    @JoinColumn(name="position_id") 
	@NotFound(action=NotFoundAction.IGNORE)
	public Set<ZPositionPower> getPosition_power() {
		return position_power;
	}
	
	public void setPosition_power(Set<ZPositionPower> position_power) {
		this.position_power = position_power;
	}
	
	public ZPosition() {
	}


	public ZPosition(String id) {
		this.id = id;
	}

	public ZPosition(String id, String name, String detail) {
		this.id = id;
		this.name = name;
		this.detail = detail;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
