package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GArea generated by hbm2java
 */
@Entity
@Table(name = "g_area", catalog = "zero")
public class GArea implements java.io.Serializable {

	private String id;
	private String name;
	private Integer totalNum;
	private Integer onlineNum;
	private Integer offlineNum;
	private Long createTime;

	public GArea() {
	}

	public GArea(String id) {
		this.id = id;
	}

	public GArea(String id, String name, Integer totalNum, Integer onlineNum, Integer offlineNum, Long createTime) {
		this.id = id;
		this.name = name;
		this.totalNum = totalNum;
		this.onlineNum = onlineNum;
		this.offlineNum = offlineNum;
		this.createTime = createTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "total_num")
	public Integer getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	@Column(name = "online_num")
	public Integer getOnlineNum() {
		return this.onlineNum;
	}

	public void setOnlineNum(Integer onlineNum) {
		this.onlineNum = onlineNum;
	}

	@Column(name = "offline_num")
	public Integer getOfflineNum() {
		return this.offlineNum;
	}

	public void setOfflineNum(Integer offlineNum) {
		this.offlineNum = offlineNum;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

}
