package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GBagItem generated by hbm2java
 */
@Entity
@Table(name = "g_bag_item", catalog = "zero")
public class GBagItem implements java.io.Serializable {

	private String id;
	private String bagId;
	private String itemId;
	private Integer number;

	public GBagItem() {
	}

	public GBagItem(String id) {
		this.id = id;
	}

	public GBagItem(String id, String bagId, String itemId, Integer number) {
		this.id = id;
		this.bagId = bagId;
		this.itemId = itemId;
		this.number = number;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "bag_id", length = 32)
	public String getBagId() {
		return this.bagId;
	}

	public void setBagId(String bagId) {
		this.bagId = bagId;
	}

	@Column(name = "item_id", length = 32)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
