package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GBuff generated by hbm2java
 */
@Entity
@Table(name = "g_buff", catalog = "zero")
public class GBuff implements java.io.Serializable {

	private String id;
	private String name;
	private String detail;
	private Integer level;
	private String effectImageId;

	public GBuff() {
	}

	public GBuff(String id) {
		this.id = id;
	}

	public GBuff(String id, String name, String detail, Integer level, String effectImageId) {
		this.id = id;
		this.name = name;
		this.detail = detail;
		this.level = level;
		this.effectImageId = effectImageId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "effect_image_id", length = 32)
	public String getEffectImageId() {
		return this.effectImageId;
	}

	public void setEffectImageId(String effectImageId) {
		this.effectImageId = effectImageId;
	}

}
