package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GEquipItem generated by hbm2java
 */
@Entity
@Table(name = "g_equip_item", catalog = "zero")
public class GEquipItem implements java.io.Serializable {

	private String id;
	private String equipId;
	private String itemId;

	public GEquipItem() {
	}

	public GEquipItem(String id) {
		this.id = id;
	}

	public GEquipItem(String id, String equipId, String itemId) {
		this.id = id;
		this.equipId = equipId;
		this.itemId = itemId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "equip_id", length = 32)
	public String getEquipId() {
		return this.equipId;
	}

	public void setEquipId(String equipId) {
		this.equipId = equipId;
	}

	@Column(name = "item_id", length = 32)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

}
