package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GItems generated by hbm2java
 */
@Entity
@Table(name = "g_items", catalog = "zero")
public class GItems implements java.io.Serializable {

	private String id;
	private String detail;
	private String name;
	private Long level;
	private Long quality;
	private Long type;
	private String icon;
	private Long status;
	private Long strength;
	private Long agility;
	private Long intellect;
	private Long lucky;
	private String profile;
	private Long property;
	private Long price;

	public GItems() {
	}

	public GItems(String id) {
		this.id = id;
	}

	public GItems(String id, String detail, String name, Long level, Long quality, Long type, String icon, Long status,
			Long strength, Long agility, Long intellect, Long lucky, String profile, Long property, Long price) {
		this.id = id;
		this.detail = detail;
		this.name = name;
		this.level = level;
		this.quality = quality;
		this.type = type;
		this.icon = icon;
		this.status = status;
		this.strength = strength;
		this.agility = agility;
		this.intellect = intellect;
		this.lucky = lucky;
		this.profile = profile;
		this.property = property;
		this.price = price;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "level")
	public Long getLevel() {
		return this.level;
	}

	public void setLevel(Long level) {
		this.level = level;
	}

	@Column(name = "quality")
	public Long getQuality() {
		return this.quality;
	}

	public void setQuality(Long quality) {
		this.quality = quality;
	}

	@Column(name = "type")
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	@Column(name = "icon", length = 50)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "status")
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Column(name = "strength")
	public Long getStrength() {
		return this.strength;
	}

	public void setStrength(Long strength) {
		this.strength = strength;
	}

	@Column(name = "agility")
	public Long getAgility() {
		return this.agility;
	}

	public void setAgility(Long agility) {
		this.agility = agility;
	}

	@Column(name = "intellect")
	public Long getIntellect() {
		return this.intellect;
	}

	public void setIntellect(Long intellect) {
		this.intellect = intellect;
	}

	@Column(name = "lucky")
	public Long getLucky() {
		return this.lucky;
	}

	public void setLucky(Long lucky) {
		this.lucky = lucky;
	}

	@Column(name = "profile", length = 50)
	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

	@Column(name = "property")
	public Long getProperty() {
		return this.property;
	}

	public void setProperty(Long property) {
		this.property = property;
	}

	@Column(name = "price")
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

}
