package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GRoleBuff generated by hbm2java
 */
@Entity
@Table(name = "g_role_buff", catalog = "zero")
public class GRoleBuff implements java.io.Serializable {

	private String id;
	private String buffId;
	private String roleId;
	private Long time;
	private Long startTime;
	private Long endTime;

	public GRoleBuff() {
	}

	public GRoleBuff(String id) {
		this.id = id;
	}

	public GRoleBuff(String id, String buffId, String roleId, Long time, Long startTime, Long endTime) {
		this.id = id;
		this.buffId = buffId;
		this.roleId = roleId;
		this.time = time;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "buff_id", length = 32)
	public String getBuffId() {
		return this.buffId;
	}

	public void setBuffId(String buffId) {
		this.buffId = buffId;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "time")
	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	@Column(name = "start_time")
	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time")
	public Long getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}

}
