package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GRoleSkill generated by hbm2java
 */
@Entity
@Table(name = "g_role_skill", catalog = "zero")
public class GRoleSkill implements java.io.Serializable {

	private String id;
	private String skillId;
	private String roleId;
	private Integer level;
	private Integer proficient;

	public GRoleSkill() {
	}

	public GRoleSkill(String id) {
		this.id = id;
	}

	public GRoleSkill(String id, String skillId, String roleId, Integer level, Integer proficient) {
		this.id = id;
		this.skillId = skillId;
		this.roleId = roleId;
		this.level = level;
		this.proficient = proficient;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "skill_id", length = 32)
	public String getSkillId() {
		return this.skillId;
	}

	public void setSkillId(String skillId) {
		this.skillId = skillId;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "proficient")
	public Integer getProficient() {
		return this.proficient;
	}

	public void setProficient(Integer proficient) {
		this.proficient = proficient;
	}

}
