package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GRoleFriend generated by hbm2java
 */
@Entity
@Table(name = "g_role_friend", catalog = "zero")
public class GRoleFriend implements java.io.Serializable {

	private String id;
	private String friendId;
	private String roleId;
	private String detail;
	private Long createTime;
	private int favor;

	public GRoleFriend() {
	}

	public GRoleFriend(String id, int favor) {
		this.id = id;
		this.favor = favor;
	}

	public GRoleFriend(String id, String friendId, String roleId, String detail, Long createTime, int favor) {
		this.id = id;
		this.friendId = friendId;
		this.roleId = roleId;
		this.detail = detail;
		this.createTime = createTime;
		this.favor = favor;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "friend_id", length = 32)
	public String getFriendId() {
		return this.friendId;
	}

	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "create_time")
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "favor", nullable = false)
	public int getFavor() {
		return this.favor;
	}

	public void setFavor(int favor) {
		this.favor = favor;
	}

}
