package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GSkillBuff generated by hbm2java
 */
@Entity
@Table(name = "g_skill_buff", catalog = "zero")
public class GSkillBuff implements java.io.Serializable {

	private String id;
	private String skillId;
	private String buffId;

	public GSkillBuff() {
	}

	public GSkillBuff(String id) {
		this.id = id;
	}

	public GSkillBuff(String id, String skillId, String buffId) {
		this.id = id;
		this.skillId = skillId;
		this.buffId = buffId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "skill_id", length = 32)
	public String getSkillId() {
		return this.skillId;
	}

	public void setSkillId(String skillId) {
		this.skillId = skillId;
	}

	@Column(name = "buff_id", length = 32)
	public String getBuffId() {
		return this.buffId;
	}

	public void setBuffId(String buffId) {
		this.buffId = buffId;
	}

}
