package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GVocationSkill generated by hbm2java
 */
@Entity
@Table(name = "g_vocation_skill", catalog = "zero")
public class GVocationSkill implements java.io.Serializable {

	private String id;
	private String vocationId;
	private String skillId;

	public GVocationSkill() {
	}

	public GVocationSkill(String id) {
		this.id = id;
	}

	public GVocationSkill(String id, String vocationId, String skillId) {
		this.id = id;
		this.vocationId = vocationId;
		this.skillId = skillId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "vocation_id", length = 32)
	public String getVocationId() {
		return this.vocationId;
	}

	public void setVocationId(String vocationId) {
		this.vocationId = vocationId;
	}

	@Column(name = "skill_id", length = 32)
	public String getSkillId() {
		return this.skillId;
	}

	public void setSkillId(String skillId) {
		this.skillId = skillId;
	}

}
