package com.zzy.domain.base;
// Generated 2016-7-18 21:58:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ZUserPosition generated by hbm2java
 */
@Entity
@Table(name = "z_user_position", catalog = "zero")
public class ZUserPosition implements java.io.Serializable {

	private String id;
	private String positionId;
	private String userId;

	public ZUserPosition() {
	}

	public ZUserPosition(String id) {
		this.id = id;
	}

	public ZUserPosition(String id, String positionId, String userId) {
		this.id = id;
		this.positionId = positionId;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "position_id", length = 32)
	public String getPositionId() {
		return this.positionId;
	}

	public void setPositionId(String positionId) {
		this.positionId = positionId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
