package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.GItems;

/**
 * GBagItem generated by hbm2java
 */
@Entity
@Table(name = "g_bag_item", catalog = "zero")
public class GBagItem implements java.io.Serializable {

	private String id;
	private Integer number;
	private GItems items;
	private String bagId;
	
	@Column(name="bag_id",length=32)
	public String getBagId() {
		return bagId;
	}

	public void setBagId(String bagId) {
		this.bagId = bagId;
	} 
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id")  
	@NotFound(action=NotFoundAction.IGNORE)
	public GItems getItems() {
		return items;
	}

	public void setItems(GItems items) {
		this.items = items;
	}

	public GBagItem() {
	}

	public GBagItem(String id) {
		this.id = id;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
