package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.GItems;

/**
 * GEquipItem generated by hbm2java
 */
@Entity
@Table(name = "g_equip_item", catalog = "zero")
public class GEquipItem implements java.io.Serializable {

	private String id;
	private GItems item;
	private String equipId;
	@Column(name="equip_id",length=32)
	public String getEquipId() {
		return equipId;
	}

	public void setEquipId(String equipId) {
		this.equipId = equipId;
	}
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id")   
	@NotFound(action=NotFoundAction.IGNORE)
	public GItems getItem() {
		return item;
	}

	public void setItem(GItems item) {
		this.item = item;
	}

	public GEquipItem() {
	}

	public GEquipItem(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
