package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.zzy.base.BaseEntity;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.GGenius;

/**
 * GRaceGenius generated by hbm2java
 */
@Entity
@Table(name = "g_race_genius", catalog = "zero")
public class GRaceGenius  extends BaseEntity implements java.io.Serializable {

	private String id;
	private GGenius genius;
	private String raceId;
	
	@Column(name="role_id",length=32)
	public String getRaceId() {
		return raceId;
	}

	public void setRaceId(String raceId) {
		this.raceId = raceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "genius_id")   
	@NotFound(action=NotFoundAction.IGNORE)
	public GGenius getGenius() {
		return genius;
	}

	public void setGenius(GGenius genius) {
		this.genius = genius;
	}

	public GRaceGenius() {
	}

	public GRaceGenius(String id) {
		this.id = id;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
