	package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.GSkill;


/**
 * GRoleSkill generated by hbm2java
 */
@Entity
@Table(name = "g_role_skill", catalog = "zero")
public class GRoleSkill implements java.io.Serializable {

	private String id;
	private Integer level;
	private Integer proficient;
    private GSkill skill;
    private String roleId;
	@Column(name="role_id",length=32)
	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "skill_id")   
	@NotFound(action=NotFoundAction.IGNORE)
    public GSkill getSkill() {   
		return skill;
	}  

	public void setSkill(GSkill skill) {
		this.skill = skill;
	}

	public GRoleSkill() {}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "proficient")
	public Integer getProficient() {
		return this.proficient;
	}

	public void setProficient(Integer proficient) {
		this.proficient = proficient;
	}

}
