package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.zzy.base.BaseEntity;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.zzy.domain.base.GRole;

/**
 * GFriendRole generated by hbm2java
 */
@Entity
@Table(name = "g_role_friend", catalog = "zero")
@JsonIgnoreProperties({"friend"})
public class GRoleFriend  extends BaseEntity implements java.io.Serializable {

	private String id;
	private String detail;
	private long createTime;
	private Integer favor;
	private GRole friend;
	private String roleId;
	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@ManyToOne
    @JoinColumn(name = "friend_id")  
	@NotFound(action=NotFoundAction.IGNORE)
	public GRole getFriend() {
		return friend;
	}

	public void setFriend(GRole friend) {
		this.friend = friend;
	}


	public GRoleFriend() {
	}

	public GRoleFriend(String id, long createTime) {
		this.id = id;
		this.createTime = createTime;
	}

	public GRoleFriend(String id,  String detail, long createTime, Integer favor) {
		this.id = id;
		this.detail = detail;
		this.createTime = createTime;
		this.favor = favor;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;  
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "create_time")
	public long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(long createTime) {
		this.createTime = createTime;
	}

	@Column(name = "favor")
	public Integer getFavor() {
		return this.favor;
	}

	public void setFavor(Integer favor) {
		this.favor = favor;
	}

}
