package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.zzy.base.BaseEntity;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.GBuff;

/**
 * GBuffRole generated by hbm2java
 */
@Entity
@Table(name = "g_role_buff", catalog = "zero")
public class GRoleBuff  extends BaseEntity implements java.io.Serializable {
	
	private String id;
	private Long time;
	private Long startTime;
	private Long endTime;
    private GBuff buff;
	private String roleId;

	@Column(name = "role_id",length=32)
	public String getRoleId() {
		return roleId;  
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

    
	@ManyToOne
    @JoinColumn(name = "buff_id")  
	@NotFound(action=NotFoundAction.IGNORE)
	public GBuff getBuff() {
		return buff; 
	}

	public void setBuff(GBuff buff) {
		this.buff = buff;
	}
	
	public GRoleBuff() {
	}

	public GRoleBuff(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	@Column(name = "time")
	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	@Column(name = "start_time")
	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time")
	public Long getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}
}