package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.GBuff;

/**
 * GSkillBuff generated by hbm2java
 */
@Entity
@Table(name = "g_skill_buff", catalog = "zero")
public class GSkillBuff implements java.io.Serializable {

	private String id;
	private GBuff buff;
	private String skillId;
	@Column(name="skill_id",length=32)
	public String getSkillId() {
		return skillId;
	}

	public void setSkillId(String skillId) {
		this.skillId = skillId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buff_id")  
	@NotFound(action=NotFoundAction.IGNORE)
	public GBuff getBuff() {
		return buff;
	}

	public void setBuff(GBuff buff) {
		this.buff = buff;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	
}
