package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.ZPower;

/**
 * ZPowerPosition generated by hbm2java
 */
@Entity
@Table(name = "z_position_power", catalog = "zero")
public class ZPositionPower implements java.io.Serializable {

	private String id;
	private ZPower power;
	private String positionId;
	@Column(name="position_id",length=32)
	public String getPositionId() {
		return positionId;
	}

	public void setPositionId(String positionId) {
		this.positionId = positionId;
	}

	@ManyToOne
    @JoinColumn(name = "power_id")   
	@NotFound(action=NotFoundAction.IGNORE)
	public ZPower getPower() {
		return power;
	}

	public void setPower(ZPower power) {
		this.power = power;
	}

	public ZPositionPower() {
	}

	public ZPositionPower(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
