package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.GRole;

/**
 * ZUserGRole generated by hbm2java
 */
@Entity
@Table(name = "z_user_g_role", catalog = "zero")
public class ZUserGRole implements java.io.Serializable {

	private String id;
	private String detail;
	private GRole role;
	private String userId;
	@Column(name="user_id",length=32)
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@ManyToOne
    @JoinColumn(name = "role_id")   
	@NotFound(action=NotFoundAction.IGNORE)
	public GRole getRole() {
		return role; 
	}

	public void setRole(GRole role) {
		this.role = role;  
	}

	public ZUserGRole() {
	}

	public ZUserGRole(String id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "detail", length = 50)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
