package com.zzy.domain.cross;
// Generated 2016-7-4 10:01:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.zzy.domain.base.ZPosition;

/**
 * ZPositionUser generated by hbm2java
 */
@Entity
@Table(name = "z_user_position", catalog = "zero")
public class ZUserPosition implements java.io.Serializable {

	private String id;
	private ZPosition position;
    private String userId;
	@Column(name="user_id",length=32)
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "position_id")   
	@NotFound(action=NotFoundAction.IGNORE)
	public ZPosition getPosition() {
		return position;
	}

	public void setPosition(ZPosition position) {
		this.position = position;
	}

	public ZUserPosition() {
	}

	public ZUserPosition(String id) {
		this.id = id;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}
 
	public void setId(String id) {
		this.id = id;
	}

}
